language: cpp
compiler:
  - gcc
# - clang
install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:boost-latest/ppa
  -
  - sudo apt-get update
  - sudo apt-get install libboost1.55 g++-4.9 gcc-4.9 build-essential libgtest-dev protobuf-compiler libprotobuf-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - 
  - wget -O cryptopp.zip http://www.cryptopp.com/cryptopp562.zip
  - unzip cryptopp.zip -d cryptopp
  - cd cryptopp
  - make && sudo make install
script:
  - cmake .
  - make
branches:
  only:
    - master
    - travis-config

